language: node_js
node_js:
  - 6
sudo: false
script:
  - npm run test
deploy:
  provider: script
  script: echo "npm credentials were revoked on 2018-07-12. We regenerated many
    credentials, but this repository had no changes in at least 18 months and
    was skipped. Reconfigure npm deployments. -omsmith"; exit 1
  on:
    tags: true
