language: node_js
node_js:
- '0.10'
sudo: false
script:
- npm run test
deploy:
  provider: npm
  api_key:
    secure: MkRLoIe0FICG3QibJEYZ7n+mDpn0zp9q00uyxrAQvcTH4RJQ+D9Xw1tdrxorJMVXpHjC8M2RcFLebziRIPxok+vYjCAPJKGHWHbqivLwjSL/aOdz72db0E1V5sKMT/zMCMuUZipaLt/4rqonCfrrMwOtgHmD02uKVy5Q+iIZDqD9mRFqNTM1m++OgHu8dkipE98UdIjIhLUq89PIbcYqmcrv3NjJAjjpIJkRf9CiAvGOVNyFP8jBIyf0rf2x2Gt3E43w7QY5cGxb01X3hfyYMGeBNEMGkvuhjtjcjxJofEIoTsU36ICoJ8hRAiyHrB3VvVYlE8KH/7pN9RwfxwrgOt6385pfGEVmxYYqR84753QUAnY5mOiXVrynt3vlZf24+E0HfkNudZKqG2RfQ6Wj4BOSzw2BwNOZdd5IX4RWJ+7Snrw7S6w6CiIPzVI0mLfkuvVov4sEpW2xk4xTWxf5g8/Dm6k1mqOlbQNHrlSHdz0YJibzlC+DL8eykxb6xAnv7YgL46AVVhhFFyAKeG/l5l38Cbmkdy5HbZTb4deaMhYpkgTlV3rSyX98jm+JCaCnyljUoLWLR9mbfB8Eg/MjPHCw7911aqctCRnWUnS0vS9neuqUd0bdYumQK6u4BalnoLdB4ubHUw2TRtoNtZqhR3KCGivCT4yCIlnFjqORc+w=
  on:
    tags: true
